// <auto-generated />
using System;
using DAW_Yacht.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAW_Yacht.Migrations.Models
{
    [DbContext(typeof(ModelsContext))]
    [Migration("20210112081053_InitialSchema2")]
    partial class InitialSchema2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("DAW_Yacht.Models.PozieModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4");

                    b.Property<int>("Strofe")
                        .HasColumnType("int");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Poezii");
                });

            modelBuilder.Entity("DAW_Yacht.Models.VolumModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4");

                    b.Property<int?>("PozieModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PozieModelId");

                    b.ToTable("Volume");
                });

            modelBuilder.Entity("DAW_Yacht.Models.VolumModel", b =>
                {
                    b.HasOne("DAW_Yacht.Models.PozieModel", null)
                        .WithMany("VolumModels")
                        .HasForeignKey("PozieModelId");
                });

            modelBuilder.Entity("DAW_Yacht.Models.PozieModel", b =>
                {
                    b.Navigation("VolumModels");
                });
#pragma warning restore 612, 618
        }
    }
}
