// <auto-generated />
using System;
using DAW_Yacht.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAW_Yacht.Migrations.Models
{
    [DbContext(typeof(ModelsContext))]
    [Migration("20210112081313_InitialSchema3")]
    partial class InitialSchema3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("DAW_Yacht.Models.PozieModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4");

                    b.Property<int>("Strofe")
                        .HasColumnType("int");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4");

                    b.Property<int?>("VolumModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VolumModelId");

                    b.ToTable("Poezii");
                });

            modelBuilder.Entity("DAW_Yacht.Models.VolumModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Volume");
                });

            modelBuilder.Entity("DAW_Yacht.Models.PozieModel", b =>
                {
                    b.HasOne("DAW_Yacht.Models.VolumModel", null)
                        .WithMany("PozieModels")
                        .HasForeignKey("VolumModelId");
                });

            modelBuilder.Entity("DAW_Yacht.Models.VolumModel", b =>
                {
                    b.Navigation("PozieModels");
                });
#pragma warning restore 612, 618
        }
    }
}
