// <auto-generated />
using DAW_Yacht.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAW_Yacht.Migrations.Models
{
    [DbContext(typeof(ModelsContext))]
    [Migration("20210112085414_DbSeed")]
    partial class DbSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("DAW_Yacht.Models.PozieModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4");

                    b.Property<int>("Strofe")
                        .HasColumnType("int");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4");

                    b.Property<int>("VolumId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VolumId");

                    b.ToTable("Poezii");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Autor = "Ion Popescu",
                            Strofe = 4,
                            Titlu = "Ursul Pacalit de Vulpe",
                            VolumId = 1
                        },
                        new
                        {
                            Id = 2,
                            Autor = "Mihai Eminovici",
                            Strofe = 98,
                            Titlu = "Luceafarul",
                            VolumId = 1
                        },
                        new
                        {
                            Id = 3,
                            Autor = "Mihai Eminovici",
                            Strofe = 98,
                            Titlu = "Luceafarul",
                            VolumId = 2
                        },
                        new
                        {
                            Id = 4,
                            Autor = "Autor 4",
                            Strofe = 4,
                            Titlu = "Pozie 4",
                            VolumId = 2
                        },
                        new
                        {
                            Id = 5,
                            Autor = "Autor 5",
                            Strofe = 5,
                            Titlu = "Poezie 5",
                            VolumId = 3
                        },
                        new
                        {
                            Id = 6,
                            Autor = "Autor 6",
                            Strofe = 6,
                            Titlu = "Pozie 6",
                            VolumId = 3
                        });
                });

            modelBuilder.Entity("DAW_Yacht.Models.VolumModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Volume");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Denumire = "Volum 1"
                        },
                        new
                        {
                            Id = 2,
                            Denumire = "Volum 2"
                        },
                        new
                        {
                            Id = 3,
                            Denumire = "Volum 3"
                        });
                });

            modelBuilder.Entity("DAW_Yacht.Models.PozieModel", b =>
                {
                    b.HasOne("DAW_Yacht.Models.VolumModel", "Volum")
                        .WithMany("PozieModels")
                        .HasForeignKey("VolumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Volum");
                });

            modelBuilder.Entity("DAW_Yacht.Models.VolumModel", b =>
                {
                    b.Navigation("PozieModels");
                });
#pragma warning restore 612, 618
        }
    }
}
